name: CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Add MSBuild to PATH
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      # Build Database project
      - name: Build Database project
        run: |
          msbuild.exe Database2/Database2.sqlproj /p:Configuration=Release

      # Upload artifact
      - name: Upload SQLDB Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: SQLDB
          path: Database2/bin/Release/

  download:
    needs: build  # Ensures this job runs after the 'build' job
    runs-on: windows-latest

    steps:
      # Checkout repository (if required, optional)
      - uses: actions/checkout@v4

      # Download SQLDB artifact
      - name: Download SQLDB Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: SQLDB
          
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          enable-AzPSSession: true
          
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.2.1
        with:
          # The connection string, including authentication information, for the Azure SQL Server database.
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: Database2.dacpac 
          # If not using a .sql file, the sqlpackage action to execute.
          action: publish
   
          
