name: CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Add MSBuild to PATH
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      # Build Database project
      - name: Build Database project
        run: |
          msbuild.exe Database2/Database2.sqlproj /p:Configuration=Release

      # Upload artifact
      - name: Upload SQLDB Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SQLDB
          path: Database2/bin/Release/

  download:
    needs: build  # Ensures this job runs after the 'build' job
    runs-on: windows-latest

    steps:
      # Checkout repository (if required, optional)
      - uses: actions/checkout@v4

      # Download SQLDB artifact
      - name: Download SQLDB Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: SQLDB

